use_frameworks!

platform :ios, '10.0'

target 'LXBaseLib_Example' do
  pod 'LXBaseLib', :path => '../'

  target 'LXBaseLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
